
const item = [{
  ItemId: 21,
  name: "Modern Accent Chair",
  category: "Chair",
  image: "https://example.com/images/modern-accent-chair.jpg",
  newPrice: 150,
  oldPrice: 200,
  color: "Gray",
  description: "A stylish accent chair that adds a modern touch to any room.",
  availability: true,
  rentalPrice: 15,
  rentalDurationOptions: [2, 4, 6],
  material: "Fabric",
  weight: 15,
  stockQuantity: 12,
  location: "Warehouse A",
  ratings: {
    averageRating: 4.7,
    numberOfRatings: 120
  }
},
{
  ItemId: 22,
  name: "Leather Office Chair",
  category: "Chair",
  image: "https://example.com/images/leather-office-chair.jpg",
  newPrice: 250,
  oldPrice: 300,
  color: "Black",
  description: "Ergonomic office chair with genuine leather for comfort.",
  availability: true,
  rentalPrice: 20,
  rentalDurationOptions: [2, 4, 6],
  material: "Leather",
  weight: 18,
  stockQuantity: 30,
  location: "Warehouse B",
  ratings: {
    averageRating: 4.8,
    numberOfRatings: 90
  }
},
{
  ItemId: 23,
  name: "Vintage Wooden Chair",
  category: "Chair",
  image: "https://example.com/images/vintage-wooden-chair.jpg",
  newPrice: 120,
  oldPrice: 160,
  color: "Brown",
  description: "Classic wooden chair with a vintage finish.",
  availability: true,
  rentalPrice: 12,
  rentalDurationOptions: [2, 4, 6],
  material: "Wood",
  weight: 10,
  stockQuantity: 25,
  location: "Warehouse C",
  ratings: {
    averageRating: 4.5,
    numberOfRatings: 85
  }
},
{
  ItemId: 24,
  name: "Plastic Stackable Chair",
  category: "Chair",
  image: "https://example.com/images/plastic-stackable-chair.jpg",
  newPrice: 45,
  oldPrice: 60,
  color: "Blue",
  description: "Durable and lightweight plastic chair ideal for events.",
  availability: true,
  rentalPrice: 5,
  rentalDurationOptions: [2, 4, 6],
  material: "Plastic",
  weight: 5,
  stockQuantity: 100,
  location: "Warehouse D",
  ratings: {
    averageRating: 4.3,
    numberOfRatings: 150
  }
},
{
  ItemId: 25,
  name: "Recliner Chair",
  category: "Chair",
  image: "https://example.com/images/recliner-chair.jpg",
  newPrice: 300,
  oldPrice: 350,
  color: "Beige",
  description: "Comfortable recliner chair with adjustable positions.",
  availability: true,
  rentalPrice: 25,
  rentalDurationOptions: [2, 4, 6],
  material: "Fabric",
  weight: 25,
  stockQuantity: 8,
  location: "Warehouse E",
  ratings: {
    averageRating: 4.6,
    numberOfRatings: 75
  }
},
{
  ItemId: 26,
  name: "Gaming Chair",
  category: "Chair",
  image: "https://example.com/images/gaming-chair.jpg",
  newPrice: 180,
  oldPrice: 220,
  color: "Red",
  description: "Ergonomic gaming chair designed for long gaming sessions.",
  availability: true,
  rentalPrice: 18,
  rentalDurationOptions: [2, 4, 6],
  material: "Synthetic Leather",
  weight: 20,
  stockQuantity: 50,
  location: "Warehouse F",
  ratings: {
    averageRating: 4.7,
    numberOfRatings: 200
  }
},
{
  ItemId: 27,
  name: "Outdoor Patio Chair",
  category: "Chair",
  image: "https://example.com/images/outdoor-patio-chair.jpg",
  newPrice: 75,
  oldPrice: 100,
  color: "Green",
  description: "Weather-resistant patio chair perfect for outdoor use.",
  availability: true,
  rentalPrice: 7,
  rentalDurationOptions: [2, 4, 6],
  material: "Metal",
  weight: 8,
  stockQuantity: 60,
  location: "Warehouse G",
  ratings: {
    averageRating: 4.4,
    numberOfRatings: 140
  }
},
{
  ItemId: 28,
  name: "Dining Room Chair",
  category: "Chair",
  image: "https://example.com/images/dining-room-chair.jpg",
  newPrice: 100,
  oldPrice: 130,
  color: "White",
  description: "Elegant dining room chair with cushioned seating.",
  availability: true,
  rentalPrice: 10,
  rentalDurationOptions: [2, 4, 6],
  material: "Wood",
  weight: 12,
  stockQuantity: 40,
  location: "Warehouse H",
  ratings: {
    averageRating: 4.6,
    numberOfRatings: 110
  }
},
{
  ItemId: 29,
  name: "Swivel Bar Stool",
  category: "Chair",
  image: "https://example.com/images/swivel-bar-stool.jpg",
  newPrice: 80,
  oldPrice: 100,
  color: "Black",
  description: "Modern bar stool with 360-degree swivel feature.",
  availability: true,
  rentalPrice: 8,
  rentalDurationOptions: [2, 4, 6],
  material: "Metal",
  weight: 10,
  stockQuantity: 70,
  location: "Warehouse I",
  ratings: {
    averageRating: 4.5,
    numberOfRatings: 130
  }
},
{
  ItemId: 30,
  name: "Folding Camping Chair",
  category: "Chair",
  image: "https://example.com/images/folding-camping-chair.jpg",
  newPrice: 40,
  oldPrice: 50,
  color: "Red",
  description: "Portable and foldable camping chair for outdoor activities.",
  availability: true,
  rentalPrice: 4,
  rentalDurationOptions: [2, 4, 6],
  material: "Fabric",
  weight: 4,
  stockQuantity: 150,
  location: "Warehouse J",
  ratings: {
    averageRating: 4.2,
    numberOfRatings: 180
  }
}],